version: 1

formatters:
  generic:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s %(levelname)-8s %(name)-18s %(message)s'

handlers:
  auth:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: auth.log
    formatter: generic
    maxBytes: 1000

  nfs:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: nfs.log
    formatter: generic
    maxBytes: 1000

  smb:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: smb.log
    formatter: generic
    maxBytes: 1000

  zone:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: zone.log
    formatter: generic
    maxBytes: 1000

  console:
    class: logging.StreamHandler
    formatter: generic
    stream: ext://sys.stdout

  main:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: main.log
    formatter: generic
    maxBytes: 1000

loggers:
  __main__:
    handlers:
    - main
    - console
    level: DEBUG
    propagate: false

  papi_cli:
    handlers:
    - main
    - console
    level: DEBUG
    propagate: false

  module.papi.auth:
    handlers:
    - auth
    - console
    level: DEBUG
    propagate: false

  module.papi.nfs:
    handlers:
    - nfs
    - console
    level: DEBUG
    propagate: false

  module.papi.smb:
    handlers:
    - smb
    - console
    level: DEBUG
    propagate: false

  module.papi.zone:
    handlers:
    - zone
    - console
    level: DEBUG
    propagate: false

root:
  handlers:
  - main
  - console
  level: DEBUG
    